### PR TITLE
Object CRUD using %JSON.Adaptor mappings

### PR DESCRIPTION
**Pull request by albertoft**
Pull requests that contains:
* Recent @henryhamon changes
* Development docker configuration
* New changes that add %JSON.Adaptor mappings support to object CRUD operations

### Instructions
Build, run container, connect to IRIS:
```
$ docker-compose build
$ docker-compose up -d
$ docker exec -it restforms2 bash
$ iris session IRIS
``` 
Run all UnitTests:
```
  zn "restforms2"
  set ^UnitTestRoot = "/app/src/UnitTests"
  do ##class(%UnitTest.Manager).RunTest("", "/nodelete")
```

`UnitTests.ObjectCRUD` contains the new added UnitTests

### CODE REVIEW

**Comment by eduard93** [comment]
Unit tests work for me, checking the code

**Comment by eduard93** [comment]
1. Why `$$$ThrowOnError`? Let's keep `%Status`, especially considering the fact that %JSON Adaptor methods are guaranteed to return `%Status` and not exception.
2. Why `App.Installer` and not `Form.Installer`? 
3. `PUT` with nonexistent object property id returns `200 OK` and destroys old property value if any. Example: `PUT {"relative":-1}` would return `200 OK`.

**Comment by albertoft** [comment]
Hi @eduard93, some comments:
1. The behaviour is still the same. A `%Status` is returned.
Every `$$$ThrowOnError` in https://github.com/intersystems-community/RESTForms2/pull/8/commits/50ccb848c840f20fde6bd6da95174cd8482759c9 is used within a `try-catch`, so it will be catched and then the `%Status` extracted using `set ret = ex.AsStatus()`. This `%Status` is returned.

So the final behaviour should be the same, for example:
```
 #dim sc As %Status = $$$OK
 set sc = ##class(Form.Info).formExistsStatus(class)
 return:$$$ISERR(sc) sc
```
should behave as:
```
set ret = $$$OK
try {
   $$$ThrowOnError(##class(Form.Info).formExistsStatus(class))
} catch ex {
   set ret = ex.AsStatus()
}
quit ret
```

2. Definitely it should be `Form.Installer` :) maybe even `UnitTests` can moved to the `Form. package`

3. I understand you have a `Form.Test.Person` with a `relative` defined property and then you try a `PUT` on this object with a non-existent object id (e.g. -1).

This very same test works as expected if you use `company` property instead of `relative`.
`"error": "ERROR #5824: Object referenced by 'Form.Test.Person.company(-1)' does not exist`

The code for `PUT` handling in `Form:Adaptor:updateFromJSON()` is:
```
   set obj = ..%OpenId(id,,.sc)
   $$$ThrowOnError(sc)
   $$$ThrowOnError(obj.%JSONImport(jsonInput, $parameter(obj,"FORMUPDATEMAPPING")))
   $$$ThrowOnError(obj.%Save())
```
It seems that `%JSON.Adaptor:%JSONImport()` is not returning errors in case a non-existent object id for the self class (`Form.Test.Person`).

As we are relying on `%JSON.Adaptor` I'm not sure how can we tackle this issue, however, I've just realized that if you add a foreign key the `PUT` we are testing now fails.
`ForeignKey RelativeFK(relative) References Form.Test.Person();` in `Form.Test.Person`

`ERROR #5829: Foreign Key constraint (Form.Test.Person.RelativeFK) failed referential integrity check upon UPDATE in referencing extent`

**Comment by eduard93** [comment]
1. Sure, but you're still doing exception object initialization inside. Please consider replacing:
```
set ret = $$$OK
try {
   $$$ThrowOnError(##class(Form.Info).formExistsStatus(class))
} catch ex {
   set ret = ex.AsStatus()
}
quit ret
```

With
```
set ret = $$$OK
try {
   set ret = ##class(Form.Info).formExistsStatus(class)
} catch ex {
   set ret = ex.AsStatus()
}
quit ret
```


In a case of several  `$$$ThrowOnError` you can use
```
set ret = ##class(Form.Info).formExistsStatus(class)
quit:$$$ISERR(ret)
```

A group of `$$$QuitOnError` macros can be used to keep it as one-liners.

2. OK.
3. Looks like a bug? Let's keep FK as a workaround for now.

**Comment by eduard93** [comment]
4. Please use `sc` for status and not `ret` for uniformity.

**Comment by eduard93** [comment]
3. You're saying that the issue is self/nonself class property:

> This very same test works as expected if you use company property instead of relative.
"error": "ERROR #5824: Object referenced by 'Form.Test.Person.company(-1)' does not exist

Consider [this model](https://gist.githubusercontent.com/eduard93/9ac734fd94f2cbd6a3a19c38847b254b/raw/cc4939d6a10b2e8a3f9005523a94a07115b5eff4/Test.xml) with one self and one non-self property:
```
Class Test.A Extends (%Persistent, %JSON.Adaptor)
{

Property A As A(%JSONINCLUDE = "INOUT", %JSONREFERENCE = "ID");

Property B As B(%JSONINCLUDE = "INOUT", %JSONREFERENCE = "ID");
}
```

```
Class Test.B Extends (%Persistent, %JSON.Adaptor)
{
}
```

And the test case:
```
/// do ##class(Test.A).Test()
ClassMethod Test()
{
	do ..%KillExtent()
	do ##class(B).%KillExtent()
	
	set obj = ..%New()
	set sc = obj.%Save()
	kill obj
	
	set obj = ..%OpenId(1)
	
	set sc = obj.%JSONImport({"B":-1})
	w "Setting B property: ", $System.Status.GetErrorText(sc),!
	set sc = obj.%Save()
	w "Saving: ", $System.Status.GetErrorText(sc),!
	
	set sc = obj.%JSONImport({"A":-1})
	w "Setting A property: ", $System.Status.GetErrorText(sc),!
	set sc = obj.%Save()
	w "Saving: ", $System.Status.GetErrorText(sc),!
}
```

For me I get identical lack of errors:
```
Setting B property:
Saving:
Setting A property:
Saving:
```

That said I also receive `Object referenced by 'Form.Test.Person.company(-1)' does not exist` error in Postman.

**Comment by eduard93** [comment]
`%JSONImport` always returns an OK status (in Postman/RESTForms or my test), it's %Save which fails (correctly) but only in Postman/RESTForms case. Why?

**Comment by eduard93** [comment]
`company` is a relationship, that's why it fails.

**Comment by albertoft** [comment]
Hi @eduard93,

I've just added some changes:
* `$$$QuitOnError` instead of try-catch + `$$$ThrowOnError`
* Returning variable `sc` for %Status
* Installer is now `Form.Installer`
* UnitTests are now `Form.UnitTests`

**Review by henryhamon — APPROVED** [review]

**Review by henryhamon — APPROVED** [review]

**Review by henryhamon — APPROVED** [review]

**Review by henryhamon — APPROVED** [review]
🚀

**Review by henryhamon — APPROVED** [review]

**Review by henryhamon — APPROVED** [review]

**Review by henryhamon — APPROVED** [review]

**Pull request merged**
